// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestData.Entities;

namespace TestData.Entities.Migrations
{
    [DbContext(typeof(TestDataContext))]
    [Migration("20190206235430_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestData.Entities.TestDataL1", b =>
                {
                    b.Property<int>("TestDataId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BatchNumber");

                    b.Property<string>("CustomerSerialNumber");

                    b.Property<string>("PartNumber");

                    b.Property<string>("SerialNumber");

                    b.HasKey("TestDataId");

                    b.ToTable("TestDatas");

                    b.HasData(
                        new
                        {
                            TestDataId = 1,
                            BatchNumber = "J123",
                            CustomerSerialNumber = "Cisco12345",
                            PartNumber = "64000236",
                            SerialNumber = "NJ123456789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
